import { redirect } from 'next/navigation';
import { PageHero, SiteShell } from '@/components/SiteShell';
import { contact } from '@/lib/site-content';
import { field, formatRows, sendPixilensEmail } from '@/lib/email';
import { PhotoboothRentalForm } from './PhotoboothRentalForm';

export const metadata = {
  title: 'Photo Booth Rental - Pixilens Photography',
};

const agreementText = `I. THE PARTIES
This Photo Booth Contract (“Agreement”) is between the client submitting this form and Photo Booth Provider: Pixilens Photography, Sole proprietor Priyanka Sarkar.

II. PHOTO BOOTH
The Provider agrees to lease the selected photo booth service for the event. Depending on the selected package, this may include iPad Photo Booth with backgrounds, backdrop stand and props, Video Guestbook, 360 Photobooth, prints, and/or attendant services.

III. EVENT INFORMATION
The Provider will arrive before the event time to set up the Photo Booth. The client is responsible for venue access, appropriate setup space, shelter, power, and any venue requirements.

IV. PAYMENT
Rent per hour for Video Guestbook and iPad Photobooth starts at $150. Rent per hour for iPad Photobooth with unlimited prints starts at $250 with attendant. Rent per hour for 360 Photobooth starts at $225. Discounts are separately discussed and provided on total cost if agreed. A non-refundable deposit of $50 is required. The balance, less any deposit, is due on the date of the event or prior. Any overage in time may be billed at $175/hour and must be paid by the end of the event. If the event ends earlier than expected, no refund will be given. Any date change request must be made in writing at least 15 days before the event and is subject to availability.

V. TERMS AND CONDITIONS
The Provider will deliver, set up, and remove the Photo Booth from the event location. The client will arrange appropriate space, shelter, power, and access. The client is responsible for any damage or loss to the Provider’s equipment due to misuse by the client or guests, theft, fire, flood, earthquake, unsafe weather, or other event conditions. If only partial services can be provided due to conditions beyond reasonable control, payments may be negotiated on a prorated basis. If the Provider fails to provide a fully operational Photo Booth for the event, the client’s remedy will be a refund for the unavailable service.

VI. RIGHTS TO PHOTOS AND MEDIA
Rights to media generated by the Photo Booth belong to Pixilens Photography. Pixilens may make media available online for the client and may use media for promotional purposes unless otherwise agreed in writing.

VII. ADDITIONAL TERMS
This is a digital photobooth with text/email delivery. Prints depend on the selected package. Delivery is subject to internet availability. If mobile signal or venue Wi-Fi is not available, text/emails may queue and send when the booth reconnects.

VIII. ENTIRE AGREEMENT
This form represents the rental agreement for the selected event. No modification or amendment is effective unless agreed in writing.

IX. EXECUTION
By submitting this form, the client confirms that all information is accurate, that they are authorized to execute this agreement, and that they agree to the photo booth rental terms.`;

type PhotoboothState = {
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  eventType: string;
  otherEventType: string;
  eventDate: string;
  eventTime: string;
  venueName: string;
  venueStreet: string;
  venueStreet2: string;
  venueCity: string;
  venueState: string;
  venueZip: string;
  setupLocation: string;
  backdrop: string;
  galleryText: string;
  agreement: string;
  signature: string;
  paymentMethod: string;
  attendantRequired: string;
  numberOfHours: string;
  area: string;
  photoboothType: string;
};

function fullName(data: PhotoboothState) {
  return `${data.firstName} ${data.lastName}`.trim();
}

function resolvedEventType(data: PhotoboothState) {
  return data.eventType === 'Other' ? data.otherEventType : data.eventType;
}

function venueAddress(data: PhotoboothState) {
  return [data.venueStreet, data.venueStreet2, data.venueCity, data.venueState, data.venueZip].filter(Boolean).join(', ');
}

function hoursMinutes(numberOfHours: string) {
  const match = numberOfHours.match(/^(\d+)/);
  return match ? String(Number(match[1]) * 60) : '';
}

function requiresBackdrop(photoboothType: string) {
  return photoboothType === 'Photobooth (IPAD)';
}

function requiresAttendant(photoboothType: string) {
  return photoboothType === 'Photobooth (IPAD)';
}

function formatText(data: PhotoboothState) {
  return `New Pixilens photo booth rental enquiry\n\nName: ${fullName(data)}\nPhone Number: ${data.phone}\nEmail: ${data.email}\nEvent Type: ${resolvedEventType(data)}\nEvent Date: ${data.eventDate}\nEvent Time: ${data.eventTime}\nVenue Name: ${data.venueName}\nVenue Address: ${venueAddress(data)}\nWhere will we be setting up?: ${data.setupLocation}\nChoose A Backdrop: ${data.backdrop || 'Not shown for selected booth type'}\nOnline Gallery Text: ${data.galleryText}\nAgreement: ${data.agreement}\nSignature: ${data.signature || 'Not provided'}\nPayment Method: ${data.paymentMethod}\nAttendant required?: ${data.attendantRequired || 'Not shown for selected booth type'}\nNumber of Hours: ${data.numberOfHours}\nHours Minutes: ${hoursMinutes(data.numberOfHours)}\nSelect Area: ${data.area}\nPhotobooth Type: ${data.photoboothType}`;
}

function formatHtml(data: PhotoboothState) {
  return `<div style="font-family:Arial,sans-serif;color:#17130f;line-height:1.5;"><h2 style="color:#a87921;">New Pixilens photo booth rental enquiry</h2><table style="border-collapse:collapse;width:100%;max-width:760px;">${formatRows([
    ['Name', fullName(data)],
    ['Phone Number', data.phone],
    ['Email', data.email],
    ['Event Type', resolvedEventType(data)],
    ['Event Date', data.eventDate],
    ['Event Time', data.eventTime],
    ['Venue Name', data.venueName],
    ['Venue Address', venueAddress(data)],
    ['Where will we be setting up?', data.setupLocation],
    ['Choose A Backdrop', data.backdrop || 'Not shown for selected booth type'],
    ['Online Gallery Text', data.galleryText],
    ['Agreement', data.agreement],
    ['Signature', data.signature || 'Not provided'],
    ['Payment Method', data.paymentMethod],
    ['Attendant required?', data.attendantRequired || 'Not shown for selected booth type'],
    ['Number of Hours', data.numberOfHours],
    ['Hours Minutes', hoursMinutes(data.numberOfHours)],
    ['Select Area', data.area],
    ['Photobooth Type', data.photoboothType],
  ])}</table></div>`;
}

async function sendPhotoboothEnquiry(formData: FormData) {
  'use server';

  const data: PhotoboothState = {
    firstName: field(formData, 'firstName'),
    lastName: field(formData, 'lastName'),
    phone: field(formData, 'phone'),
    email: field(formData, 'email'),
    eventType: field(formData, 'eventType'),
    otherEventType: field(formData, 'otherEventType'),
    eventDate: field(formData, 'eventDate'),
    eventTime: field(formData, 'eventTime'),
    venueName: field(formData, 'venueName'),
    venueStreet: field(formData, 'venueStreet'),
    venueStreet2: field(formData, 'venueStreet2'),
    venueCity: field(formData, 'venueCity'),
    venueState: field(formData, 'venueState'),
    venueZip: field(formData, 'venueZip'),
    setupLocation: field(formData, 'setupLocation'),
    backdrop: field(formData, 'backdrop'),
    galleryText: field(formData, 'galleryText'),
    agreement: field(formData, 'agreement'),
    signature: field(formData, 'signature'),
    paymentMethod: field(formData, 'paymentMethod'),
    attendantRequired: field(formData, 'attendantRequired'),
    numberOfHours: field(formData, 'numberOfHours'),
    area: field(formData, 'area'),
    photoboothType: field(formData, 'photoboothType'),
  };

  if (!data.firstName || !data.lastName || !data.phone || !data.email || !data.eventType || (data.eventType === 'Other' && !data.otherEventType) || !data.eventDate || !data.eventTime || !data.venueName || !data.venueStreet || !data.venueCity || !data.venueState || !data.venueZip || !data.setupLocation || (requiresBackdrop(data.photoboothType) && !data.backdrop) || !data.galleryText || data.agreement !== 'Yes I Agree' || !data.paymentMethod || (requiresAttendant(data.photoboothType) && !data.attendantRequired) || !data.numberOfHours || !data.area || !data.photoboothType) {
    redirect('/Photobooth-Enquiry?status=missing');
  }

  const sent = await sendPixilensEmail({
    toUser: data.email,
    userName: fullName(data),
    subject: `Pixilens photo booth rental from ${fullName(data)}`,
    text: formatText(data),
    html: formatHtml(data),
  });

  redirect(sent ? '/Photobooth-Enquiry?status=sent' : '/Photobooth-Enquiry?status=email-not-configured');
}

export default async function PhotoboothEnquiryPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const params = await searchParams;
  return (
    <SiteShell>
      <PageHero eyebrow="Photo Booth Rental" title="Photo Booth Rental">
        <p>Complete the rental form with your event details, booth type, setup requirements, payment method, and agreement.</p>
      </PageHero>

      <section className="mx-auto max-w-5xl px-5 pb-20 md:px-8">
        {params.status === 'sent' ? <div className="glass-panel mb-8 rounded-xl p-5 text-center text-[#17130f]/75">Thank you. Your photo booth rental form was sent to Pixilens and a confirmation email was sent to you.</div> : null}
        {params.status === 'missing' ? <div className="glass-panel mb-8 rounded-xl border-red-200/70 p-5 text-center text-red-700">Please fill out all required fields before sending.</div> : null}
        {params.status === 'email-not-configured' ? <div className="glass-panel mb-8 rounded-xl border-red-200/70 p-5 text-center text-red-700">Email sending is not configured yet. Please email {contact.email} directly.</div> : null}
        <PhotoboothRentalForm action={sendPhotoboothEnquiry} agreementText={agreementText} />
      </section>
    </SiteShell>
  );
}
