import { redirect } from 'next/navigation';
import { PageHero, SiteShell } from '@/components/SiteShell';
import { contact } from '@/lib/site-content';
import { field, formatRows, htmlEscape, sendPixilensEmail } from '@/lib/email';

export const metadata = {
  title: 'Photo Booth Rental - Pixilens Photography',
};

const eventTypes = ['Wedding', 'Birthday Party', 'Quinceanera', 'Sweet 16', '18th Debut', '1st Birthday', 'Baby Shower', 'Bar & Bat Mitzvah', 'Prom', 'Graduation', 'Christening', 'Corporate', 'Halloween', 'Christmas', 'Fundraiser', 'Festival'];
const setupOptions = ['Indoors', 'Outdoors', 'Both'];
const paymentOptions = ['Zelle - 737 231 0033 (Pixilens LLC) [Preferred]', 'CashApp - https://cash.app/$pixilensphotography'];
const attendantOptions = ['Yes', 'No'];
const hourOptions = ['2 hours', '3 hours', '4 hours', '5 hours', '6 hours'];
const areas = ['Austin and Surrounding cities (TX)', 'Phoenix and Surrounding cities (AZ)'];
const boothTypes = ['360 Photobooth', 'Video Guest Book', 'Photobooth (IPAD)'];

const agreementText = `Photo Booth Provider: Pixilens Photography, Sole proprietor Priyanka Sarkar.

Pixilens will deliver, set up, and remove the photo booth from the event location. The client will arrange appropriate space, venue access, power, and setup conditions. A non-refundable $50 deposit is required to reserve the event date. The remaining balance is due before setup or on the event date.

Rental rates may vary by package: Video Guestbook and iPad Photobooth, iPad Photobooth with unlimited prints and attendant, and 360 Photobooth. Discounts or custom pricing must be agreed separately. Any overage in time may be billed at the event rate.

The client is responsible for damage or loss to Pixilens equipment caused by misuse, guests, unsafe conditions, theft, fire, flood, or similar causes. Pixilens may stop operation if weather or conditions are unsafe for equipment or attendees.

All media generated by the photo booth is the property of Pixilens Photography. Pixilens may make media available to the client online and may use event media for promotional purposes unless otherwise agreed in writing.

This agreement is governed by the laws of the state where the event takes place. By submitting this form, the client confirms that the information is accurate and agrees to the photo booth rental terms.`;

type PhotoboothState = {
  name: string;
  phone: string;
  email: string;
  eventType: string;
  eventDate: string;
  venueName: string;
  venueAddress: string;
  setupLocation: string;
  backdrop: string;
  galleryText: string;
  agreement: string;
  signature: string;
  paymentMethod: string;
  attendantRequired: string;
  hoursNumber: string;
  numberOfHours: string;
  area: string;
  photoboothType: string;
};

function formatText(data: PhotoboothState) {
  return `New Pixilens photo booth rental enquiry\n\nName: ${data.name}\nPhone Number: ${data.phone}\nEmail: ${data.email}\nEvent Type: ${data.eventType}\nEvent Date: ${data.eventDate}\nVenue Name: ${data.venueName}\nVenue Address: ${data.venueAddress}\nWhere will we be setting up?: ${data.setupLocation}\nChoose A Backdrop: ${data.backdrop}\nOnline Gallery Text: ${data.galleryText}\nAgreement: ${data.agreement}\nSignature: ${data.signature || 'Not provided'}\nPayment Method: ${data.paymentMethod}\nAttendant required?: ${data.attendantRequired}\nHours: ${data.hoursNumber}\nNumber of Hours: ${data.numberOfHours}\nSelect Area: ${data.area}\nPhotobooth Type: ${data.photoboothType}`;
}

function formatHtml(data: PhotoboothState) {
  return `<div style="font-family:Arial,sans-serif;color:#17130f;line-height:1.5;"><h2 style="color:#a87921;">New Pixilens photo booth rental enquiry</h2><table style="border-collapse:collapse;width:100%;max-width:760px;">${formatRows([
    ['Name', data.name],
    ['Phone Number', data.phone],
    ['Email', data.email],
    ['Event Type', data.eventType],
    ['Event Date', data.eventDate],
    ['Venue Name', data.venueName],
    ['Venue Address', data.venueAddress],
    ['Where will we be setting up?', data.setupLocation],
    ['Choose A Backdrop', data.backdrop],
    ['Online Gallery Text', data.galleryText],
    ['Agreement', data.agreement],
    ['Signature', data.signature || 'Not provided'],
    ['Payment Method', data.paymentMethod],
    ['Attendant required?', data.attendantRequired],
    ['Hours', data.hoursNumber],
    ['Number of Hours', data.numberOfHours],
    ['Select Area', data.area],
    ['Photobooth Type', data.photoboothType],
  ])}</table></div>`;
}

async function sendPhotoboothEnquiry(formData: FormData) {
  'use server';

  const data: PhotoboothState = {
    name: field(formData, 'name'),
    phone: field(formData, 'phone'),
    email: field(formData, 'email'),
    eventType: field(formData, 'eventType'),
    eventDate: field(formData, 'eventDate'),
    venueName: field(formData, 'venueName'),
    venueAddress: field(formData, 'venueAddress'),
    setupLocation: field(formData, 'setupLocation'),
    backdrop: field(formData, 'backdrop'),
    galleryText: field(formData, 'galleryText'),
    agreement: field(formData, 'agreement'),
    signature: field(formData, 'signature'),
    paymentMethod: field(formData, 'paymentMethod'),
    attendantRequired: field(formData, 'attendantRequired'),
    hoursNumber: field(formData, 'hoursNumber'),
    numberOfHours: field(formData, 'numberOfHours'),
    area: field(formData, 'area'),
    photoboothType: field(formData, 'photoboothType'),
  };

  if (!data.name || !data.phone || !data.email || !data.eventType || !data.eventDate || !data.venueName || !data.venueAddress || !data.setupLocation || !data.backdrop || !data.galleryText || data.agreement !== 'Yes I Agree' || !data.paymentMethod || !data.attendantRequired || !data.hoursNumber || !data.numberOfHours || !data.area || !data.photoboothType) {
    redirect('/Photobooth-Enquiry?status=missing');
  }

  const sent = await sendPixilensEmail({
    toUser: data.email,
    userName: data.name,
    subject: `Pixilens photo booth rental from ${data.name}`,
    text: formatText(data),
    html: formatHtml(data),
  });

  redirect(sent ? '/Photobooth-Enquiry?status=sent' : '/Photobooth-Enquiry?status=email-not-configured');
}

export default async function PhotoboothEnquiryPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const params = await searchParams;
  return (
    <SiteShell>
      <PageHero eyebrow="Photo Booth Rental" title="Photo Booth Rental">
        <p>Complete the rental form with your event details, booth type, setup requirements, payment method, and agreement.</p>
      </PageHero>

      <section className="mx-auto max-w-5xl px-5 pb-20 md:px-8">
        {params.status === 'sent' ? <div className="glass-panel mb-8 rounded-xl p-5 text-center text-[#17130f]/75">Thank you. Your photo booth rental form was sent to Pixilens and a confirmation email was sent to you.</div> : null}
        {params.status === 'missing' ? <div className="glass-panel mb-8 rounded-xl border-red-200/70 p-5 text-center text-red-700">Please fill out all required fields before sending.</div> : null}
        {params.status === 'email-not-configured' ? <div className="glass-panel mb-8 rounded-xl border-red-200/70 p-5 text-center text-red-700">Email sending is not configured yet. Please email {contact.email} directly.</div> : null}

        <form action={sendPhotoboothEnquiry} className="glass-panel rounded-xl p-6 md:p-9">
          <div className="grid gap-5 md:grid-cols-2">
            <label className="public-label md:col-span-2">Name *<input name="name" required className="public-input" /></label>
            <label className="public-label">Phone Number *<input name="phone" required className="public-input" /></label>
            <label className="public-label">Email *<input name="email" type="email" required className="public-input" /></label>
            <label className="public-label">Event Type *<select name="eventType" required className="public-input public-select"><option value="">Please Select</option>{eventTypes.map((item) => <option key={item}>{item}</option>)}</select></label>
            <label className="public-label">Event Date *<input name="eventDate" type="date" required className="public-input public-date" /></label>
            <label className="public-label">Venue Name *<input name="venueName" required className="public-input" /></label>
            <label className="public-label">Where will we be setting up? *<select name="setupLocation" required className="public-input public-select"><option value="">Please Select</option>{setupOptions.map((item) => <option key={item}>{item}</option>)}</select></label>
            <label className="public-label">Choose A Backdrop *<input name="backdrop" required className="public-input" placeholder="Describe preferred backdrop or write undecided" /></label>
            <label className="public-label">Attendant required? Extra $50 per hour *<select name="attendantRequired" required className="public-input public-select"><option value="">Please Select</option>{attendantOptions.map((item) => <option key={item}>{item}</option>)}</select></label>
            <label className="public-label">Hours *<input name="hoursNumber" type="number" min="1" required className="public-input" /></label>
            <label className="public-label">Number of Hours *<select name="numberOfHours" required className="public-input public-select"><option value="">Please Select</option>{hourOptions.map((item) => <option key={item}>{item}</option>)}</select></label>
            <label className="public-label">Select Area *<select name="area" required className="public-input public-select"><option value="">Please Select</option>{areas.map((item) => <option key={item}>{item}</option>)}</select></label>
            <label className="public-label">Photobooth Type *<select name="photoboothType" required className="public-input public-select"><option value="">Please Select</option>{boothTypes.map((item) => <option key={item}>{item}</option>)}</select></label>
          </div>

          <label className="public-label mt-7 block">Venue Address *<textarea name="venueAddress" required className="public-input min-h-28" /></label>
          <label className="public-label mt-7 block">What do you want the text to say in the Online Gallery? *<textarea name="galleryText" required className="public-input min-h-28" /></label>
          <label className="public-label mt-7 block">Payment Method for Deposit of $50. Rest of the remaining payment should be done prior to setting up Photobooth at the Event. We accept cash also for balance dues. *<select name="paymentMethod" required className="public-input public-select"><option value="">Please Select</option>{paymentOptions.map((item) => <option key={item}>{item}</option>)}</select></label>

          <div className="mt-8 rounded-xl border border-[#281f16]/10 bg-white/55 p-5 text-sm leading-7 text-[#17130f]/68">
            <p className="font-art gold-text text-xl">Photobooth rental agreement</p>
            <p className="mt-3 whitespace-pre-line">{agreementText}</p>
            <label className="mt-5 flex items-center gap-3 text-[#17130f]/78"><input name="agreement" value="Yes I Agree" type="checkbox" required className="accent-[#a87921]" /> Yes I Agree</label>
          </div>

          <label className="public-label mt-7 block">Sign here<input name="signature" className="public-input" placeholder="Type your full name as signature" /></label>
          <button className="glass-button mt-7" type="submit">Submit</button>
        </form>
      </section>
    </SiteShell>
  );
}
